### ISSUE TITLE
[Site theme] CSS bugs and TODO for docs site

### ISSUE THREAD

**Issue by bianchi-dy** [spatialnetworkslab/florence#136]
- [ ] Find out why size of site keeps resizing from narrow to full screen -> standardise to one size
- [ ] Fix REPL and gallery side nav bar to both use SideNav.svelte
- [ ] Change CodeBox code bit to Code component -> question of how to pass slot content down two levels of child components or to retain current structure
- [ ] Figure out repetitive styling for main col and side nav. One approach would be to create a `MainCol.svelte` components and move some of the styling from `_layout.svelte` into `Sidenave.svelte` -> again, there is the question of passing slot content down two levels
- [ ] How to make the interactivity tables + the executable a compact component – tables lose their formatting when passed on to components as slot input
- [ ] Make more versions of the warning component we currently have - like ones for tip, success, etc
- [ ] Change CodeBox code to extract directly from executable file -> takes url or location as input

Refer to branch `clean-site`.
